@startuml

left to right direction

package "Smart Contracts" {

    package "Permissioning" {

        component [Role Control]
        note right of [Role Control]
          Control roles assigned to ethereum accounts
          - single role per account
          - all contracts (except Ethereum Did Registry) depends on Role Control contract
          - all state modifying contract methods are restricted to specific roles
        end note

        component [Account Control]
        note right of [Account Control]
          **Besu specific**
          Top level control whether to accept write transactions
          - only senders with 'trustee' role can deploy new contracts
          - only senders with not-empty roles can write transactions
        end note

        component [Validator Control]
        note right of [Validator Control]
          **Besu specific**
          Control the list of network validator nodes
          - only steward can add/remove nodes
        end note

        component [Upgrade Control]
        note right of [Upgrade Control]
          Control versions of deployed contracts
          - UUPS proxy pattern
          - all contracts depends on Upgrade Control contract
          - define common rules for contracts upgrade
        end note
    }

    package "Identity" {

       package "DID" {

            component [IndyBesu Did Registry]
            note bottom of [IndyBesu Did Registry]
              Manage `indybesu` DID method records
              - did doc stored in the contract storage
              - one-to-one relationship with account
            end note

            component [Ethereum Did Registry]
            note bottom of [Ethereum Did Registry]
              Manage `ethr` DID method records
              - DID identifier is an account address
              - one-to-one relationship with account
              - `did:ethr` spec implies that DID exist by default
              - uses events approach
              - extended to control versioning
            end note

            component [Universal Did Resolver]
            note bottom of [Universal Did Resolver]
              Resolve Issuer DID from various DID registries
              - used by AnonCreds contracts to verify did existence and owner
            end note
        }

        package "Anoncreds" {

            component [Schema Registry]
            note bottom of [Schema Registry]
              Store AnonCreds schemas
            end note

            component [Credential Definition Registry]
            note top of [Credential Definition Registry]
              Store AnonCreds Credential Definitions
            end note
        }

        package "Migration" {
            component [Legacy Mapping Registry]
            note bottom of [Legacy Mapping Registry]
              Store Mapping for legacy DID/Schema/CredentialDefinition identifiers
            end note
        }
    }

    [Identity] --> [Role Control]
    [Identity] --> [Upgrade Control]
    [Universal Did Resolver] --> [IndyBesu Did Registry]
    [Universal Did Resolver] --> [Ethereum Did Registry]
    [Schema Registry] --> [Universal Did Resolver]
    [Credential Definition Registry] --> [Universal Did Resolver]
    [Legacy Mapping Registry] --> [Universal Did Resolver]
}

@enduml
