pub mod credential_definition_registry;
pub mod did_ethr_registry;
pub mod did_indy_registry;
pub mod did_resolver;
pub mod endorsing;
pub mod legacy_mapping_registry;
pub mod role_control;
pub mod schema_registry;
pub mod validator_control;
